// ModPulse — Daily Digest Job
// Sends modmail with a summary of the last 24 hours

import type { TriggerContext } from '@devvit/public-api';
import { KEYS, JOB_NAMES } from '../constants.js';

export async function handleDailyDigest(_event: unknown, context: TriggerContext): Promise<void> {
  const { redis, reddit, scheduler } = context;

  // Get stats
  const statsRaw = await redis.get(KEYS.global.stats());
  const stats = statsRaw ? JSON.parse(statsRaw) : {};

  // Get mod actions from last 24 hours
  const actionsRaw = await redis.get(KEYS.global.modActions());
  const actions = actionsRaw ? JSON.parse(actionsRaw) : [];
  const last24h = actions.filter((a: any) => Date.now() - a.timestamp < 86400000);

  // Get user counts from hashes
  const trackedMap = await redis.hGetAll(KEYS.global.trackedUsers());
  const flaggedMap = await redis.hGetAll(KEYS.global.flaggedUsers());
  const trackedCount = Object.keys(trackedMap).length;
  const flaggedCount = Object.keys(flaggedMap).length;

  // Build digest
  const lines: string[] = [];
  lines.push('## ModPulse Daily Digest');
  lines.push(`Date: ${new Date().toISOString().split('T')[0]}`);
  lines.push('');
  lines.push(`- Tracked Users: ${trackedCount}`);
  lines.push(`- Flagged Users: ${flaggedCount}`);
  lines.push(`- Mod Actions (24h): ${last24h.length}`);
  lines.push(`- Last Scan: ${stats.lastScan || 'Never'}`);
  lines.push('');

  if (last24h.length > 0) {
    lines.push('### Recent Mod Actions');
    for (const action of last24h.slice(-10)) {
      lines.push(`- ${action.action} at ${new Date(action.timestamp).toLocaleString()}`);
    }
  }

  lines.push('');
  lines.push('*Generated by ModPulse*');

  // Send modmail
  try {
    const subreddit = await reddit.getCurrentSubreddit();
    await reddit.sendPrivateMessage({
      to: `r/${subreddit.name}`,
      subject: 'ModPulse Daily Digest',
      text: lines.join('\n'),
    });
  } catch {
    // Modmail might fail
  }

  // Schedule next digest (tomorrow at 9 AM UTC)
  const tomorrow = new Date();
  tomorrow.setUTCHours(9, 0, 0, 0);
  tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);

  await scheduler.runJob({
    name: JOB_NAMES.DAILY_DIGEST,
    data: {},
    runAt: tomorrow,
  });
}
